---
title: "14.750 Problem Set 3"
author: "Wonjae Lee"
date: "April 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

## Answer 1.a

```{r}
library(tidyverse)
library(stargazer)

setwd("C:/Users/wonja/Documents/GitHub/14.750/PS3")
rm(list = ls())
load("votingData.RData")

model1 <- lm(formula =  votePercent ~ campaignDonation, data = votingData)
summary(model1)
print(paste("standard deviation of campaign donation = ", sd(votingData$campaignDonation)))
```

```{r}
stargazer(model1, type = "latex", out = "PS3-1a.tex", covariate.labels = "Campaign donation", dep.var.labels = "Percent of votes")
```

## Answer 1.b

```{r}
ggplot(data = votingData, aes(x = campaignDonation, y = votePercent)) +
  labs(x = "Campaign donation", y = "Percent of votes") +
  geom_point() +
  geom_smooth(method = lm, se = FALSE)
ggsave(filename = "PS3-1b.png")
```

## Answer 1.c

```{r}
model2 <- lm(formula = votePercent ~ campaignDonation + factor(county), data = votingData)
summary(model2)
```

```{r}
stargazer(model2, type = "latex", out = "PS3-1c.tex", covariate.labels = "Campaign donation", dep.var.labels = "Percent of votes", add.lines = list(c("County fixed effect", "Yes"), c("","")), keep = "campaignDonation", table.layout = "=ld-t-a-s=n")
```

## Answer 1.e

```{r}
county10 <- votingData %>% filter(county == 10)
county50 <- votingData %>% filter(county == 50)
ggplot(data = NULL, aes(x = campaignDonation, y = votePercent)) +
  labs(x = "Campaign donation", y = "Percent of votes") +
  geom_point(data = county10) +
  geom_smooth(data = county10, method = lm, se = FALSE) +
  geom_point(data = county50) +
  geom_smooth(data = county50, method = lm, se = FALSE)
ggsave(filename = "PS3-1e.png")
```
